#!/usr/bin/env bash
# Requirements:

# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
# As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# You can’t use systemctl for restarting nginx

# Check if nginx is installed

# Update package index and install nginx
apt-get update
apt-get install -y nginx

# Modify nginx configuration to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Restart nginx without using systemctl
kill -s HUP $(pgrep nginx)

# Create index.html with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html

service nginx restart
