#!/usr/bin/env bash
# Read the /etc/passwd file line by line using while loop

while IFS=: read -r username _ uid gid info home_dir shell; do
    # Print the desired contents
    echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $info"
done < /etc/passwd
