#!/bin/bash
# Use awk to extract visitor IP and HTTP status code from the Apache log file,
# count occurrences, and sort the data

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'