#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but on 9th say "Hi"

i=1

while [ $i -le 10 ]; do
    if [ $i -gt 9 ]; then
        echo "Hi"
    fi
    echo "Best School"
    ((i++))
done