#!/usr/bin/env bash
#prints minutes and hours

hour=0

while [ $hour -le 12 ]; do
    min=1
    echo "Hour: $hour"
    while [ $min -le 59 ]; do
        echo "$min"
        ((min++))
    done

    min=0
    ((hour++))
done
