#!/usr/bin/env bash
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

for file in *; do
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
        file_name=$(echo "$file" | cut -d'-' -f2-)
        echo "$file_name"
    fi
done