#!/usr/bin/env bash
# Update /etc/hosts file

# # Check if script is running in Docker
# if [ -f /.dockerenv ]; then
#     echo "Running in Docker container."
# else
#     echo "This script is intended to run inside a Docker container."
#     exit 1
# fi

# Update /etc/hosts file
sudo sed -i 's/^127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts

# Add mapping for facebook.com
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null

echo "Configuration completed."
